# config.yaml
# support multiple models and configurations

# default config name
default_data_config: sts_task
default_architecture_config: nvembed-7b

# GPU config
gpu_config:
  cuda_visible_devices: "0,1,2,3,4,5,6,7"


data:
  sts_task:
    tasks: "sts16-sts, sts15-sts, sts14-sts, sts13-sts, sts12-sts"
    batch_size: 64
    max_length: 512
    
  retrieval_task:
    tasks: "SCIDOCS" #ClimateFEVER, #ArguAna #DBPedia, #FiQA2018 #ArguAna,FiQA2018,NFCorpus,SciFact,
    query_batch_size: 16
    document_batch_size: 16
    max_length: 512


  long_context_task:
    tasks: "2wikimqa,summ_screen_fd,qmsum" #narrativeqa #,,
    query_batch_size: 16
    document_batch_size: 1
    max_length: 8192


  long_context_synthetic_task:
    tasks: "needle,passkey"
    context_length: 256
    query_batch_size: 16
    document_batch_size: 2
    max_length: 256


architectures:
  qwen3-embed-8b:
    model_name_or_path: "Qwen/Qwen3-Embedding-8B"

  nvembed-7b:
    model_name_or_path: "nvidia/NV-Embed-v2"

  e5-mistral:
    model_name_or_path: "intfloat/e5-mistral-7b-instruct"

  llm2vec:
    model_name_or_path: "McGill-NLP/LLM2Vec-Mistral-7B-Instruct-v2-mntp-unsup-simcse"
